SELECT u.ID, SUM(r.TOTAL_SPENT) as Money_Spent  FROM 
((SELECT * FROM Fetch_data.dbo.users) u
INNER JOIN
(SELECT PURCHASE_DATE, USER_ID, TOTAL_SPENT FROM   Fetch_data.dbo.receipts
WHERE REWARDS_RECEIPT_STATUS != 'REJECTED') r
ON u.ID = r.USER_ID) 
WHERE MONTH(r.PURCHASE_DATE) = 08
GROUP BY u.ID
ORDER BY Money_Spent DESC

