SELECT b.NAME, sum(TOTAL_FINAL_PRICE) as Dollar_Spending  FROM
(((SELECT PURCHASE_DATE, ID FROM Fetch_data.dbo.receipts
WHERE REWARDS_RECEIPT_STATUS != 'REJECTED') r
INNER JOIN
(SELECT TOTAL_FINAL_PRICE, BRAND_CODE, REWARDS_RECEIPT_ID FROM Fetch_data.dbo.receipt_items) ri
ON r.ID = ri.REWARDS_RECEIPT_ID)
INNER JOIN 
(SELECT BRAND_CODE, NAME, CATEGORY_CODE FROM Fetch_data.dbo.brands) b
ON ri.BRAND_CODE = b.BRAND_CODE)
WHERE MONTH(r.PURCHASE_DATE) = 06
GROUP BY  b.NAME
ORDER BY Dollar_Spending DESC


